###
avatar: data:image/jpg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAB+AH4DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD0Wz1ua2bZMPNjH5it+11S0ugAkqhv7jDBrGbw/PnieP8A75NRtoF0OjRH8SK9OcaM9U7HmwdaHS51Ofp+VGfp+Vcullq9tzEzY9FfP86c2qatbczR5A/vR/1FZewv8LTNfb/zJo6b8vyo/L8q5xPEkuPnt0PurEVKPEq97Vvwak8PU7D9vT7m9+X5Ufl+VYq+I7c/eilX8Aaf/b1kepk/74qfY1Ow/aw7mvn6flS5+n5VlDXbLH32/wC+DS/27Zf89G/74NL2U+w/aw7mnn6flRn6flWZ/btj/ff/AL4NI2v2Q6Fz/wABo9lPsHtYdzUz9Pypc/T8qxT4itu0UhqJvEg/gtj+LVSoVH0E60F1N7A9B+VLgYPArm38RzH7kCD6nNRDXr1yeY19gtV9WqE/WIHQtLGDzIg/4EKja6t16zxD/gQrkWUbjSba1WGXcx+tPsdS+p2aDm4U/Tmqk/iC0jyqgu3oxC/zrAkjZ43RW2sykBvQ+tefJZW4tTM2YnAJkLHdgjrndnuDSnThTtfU0p1JVL20PRJZFmmeTCpn5iq9BWLP4iskcx2qy3jjgmADYD/vnA/LNcpDZG8CS3iKIwMRxBduR2Lj/wBl6VpgBVCqAFAwABwKbxLStFCWGje8ncvf27euflsoIx/tzFj+gH86jOq6mT/rbZfYQk/+zVWorN16j6mio010Li6zfrwyW0n0DL/U1MNfkVsSWLFP70UoJ/I4/nWbRTVea6g6FN9DVfxLp6hVUytO3SFk2N/49x+WamstXjuZ1gmjMMrg7RuyGI7Z9cc/nWDJFHMhSVFdT2YZFUp7ee2izaO7KhDKhOWQjkFCfQ9jVfWZXIeFhbQ73FGBUGm3iajplteIMLNGGxjoe4/A5q1XapKxwtNOwgA3DOSueR610lnd6asWIikXqGGD+feud2ORwjflUkcUnP7tv++TWVWEZ7s0pycHsHll5NqqWJ7CpBY3B/gx9TTGyG4yPxpwnmXpIw/Gm79CY8vUf/Z9x6L/AN9Vwep2jQ+Iby0ba0CSCZsHPzMA238Dk/iK7W81OSysp7qSRtkMZc++B0rh4vNKmSdt9xKxkmb1duT/AIfhXNWbtZnXh1HVxJKbJIkMbSSuqIvJZjgCnVVvtTh8PaPHrs8CXF7cyNHpVvKMogX707DufT8PU15+IrqjFO129Eu7/rc7KcOdl2G01K6QSWmk3s8bcq4QIp+m8iorjzrH/j/s7mzB/injwn/fQyv6155feLvEWpTGW61m8JJztjlMaj6BcCrWm+PPEult+71SW4iP3obv96jD055/I1xqtjVq1F+Wv5/8A39lTsd37jkUVXs7q01LSYNY0+EW9vNKYLq0ByttP1+X/YbsOxx61YruoVlWhzLTo12Zzzg4uwU1BNLALiNIo7XOBdXc6wRMf9lm5b8ARU9pbR3moQ29wdtsFae5P/TJBlh+PA/E15d4g1y58SarJf3R/dk4t4f4YY/4VUduKwrV5up7KluldvtfY1p001zM9j0Cd4JCJpLG8stpcnT7oTNEc9SuASvXOAcV20QgMavCEKMMqyYwQe+a+V7eaW0uY7m1laC4iYNHLGcMpHfNe4+FNYbVNLgnGEM0XnbEPCOGKyKPbcNwHo9bYarV51SqyvfZ2t8jHEU4wXPFHd9qevSsQXEwHErfnT0uZ+f3rV6PsX3ONV4kbL8x5pNvvT2B3dKbW12YGR4kQtokiDJDyxq303gn+Vc9XR+I5Gi0kAZG+eNPqCf/AK1c5XLXfvHZQ+AZMSIJCv3ghI+uK534lHb/AMIzAv8AqU0lGQ9iTjP8hXS1T1XSE8TaPa6V5qQapYFvsEkxxHcRnkxFuzDtn0Hvjx8cnGdOs9ot38rrc7qDWqPLaK1L7w1r2myGO70a+jIOMiEsp+hXINOsPC+v6nKkdpo96244DvCUUfVmwAKftqfLzcyt6mtmdP8AD9lbQPE0M8rRWwFtIZAu7YwfGQO5rpzLpIyItInuueJL+6K599icD6VXh0iDw1okfh+KVZ72WZbnUpk+6pX7kY/HH4AnvWVrNtrM4T+y7qOFAPmXozH/AHiDXPhqEcQp1W2ot6WbV9Er6a9Cak+VpHS6XHDe6hc2UNjBZPd6dPArRTOwJO3s3TvyPSvFZIJbWaS2nQxzQsY5EPVWHBFen6R9utrKzne7WW+hbzVm6rnng+owSDUniPR/DviiT+0ZLxtC1VgBMJYi8Mp9cjr9QQfUVM4PB13JRbhJLXVtNd93YcJc8bPdHlVet/DeN00K03ZAc3Lrn+7vjGfzBrlYPBemJODd+JoJ4V6x6dbySSv7AkBR9TXf+GrhZpJI7Sw8iG2VLZIzINtvEMkLnq7kklj0zxniu3DS9tWg4J2WrdrdPMyxNlSafU6TFPRevNGKco61712eMhWB3Um01I33uKT8Km4WMTxLBJLpsRQZEU6yP9ACP5kVzldnqlq95pd1BFxI0Z2f7w5H6gVxMUgliWRcgMM4Pb2rnrLW510H7tiF7+1jYq0w3A4IAJxUitDdQnG2SJuCCOD+dEsk6sEhhDZH32fCj+pqRd+weZtL4529KxNya3vL+zjEdrqd5DGBgIJdwH03ZolvtTuAVm1e+dSMFRIEB/75ANRUVzPB4dvm9mr+iNPay7jI40ijCRqFUdAKeODn0oqpcwSXc6wv8toBlwDzKf7v+76+vHvXQRcbphUWaRblLKW+UHnbuOD9MVdHHSopLaKTYdgVo/uMvBX2Ht7VLTC4ZJ65q9oFsZtUux9quYh5KNticKMhmHPHNUa3fC8Klru6DZORCRjpjn/2YVdP4jOs/cN7bgdaei8HNFOXvxXXc4bDm+9SU5vvdKTj0qR2Erl9Z0OWOeS+sIjIkh3TQL1Dd3T1z3H4iupxRSlFNWZUZOLujzwHIBwRn1GDS1veKbi02paiJZL91yrgkGFf7xI/Qdz7A1y5gulH7q8Jx2mjDZ/EYrmlGzsdkHzK5aoqpuv16w20n+7Iy/zBq0pYqCyhW7gHOKkoWiiigAoopkoVkKuxCt8vBwaAJLeKe/uPs1inmSA4eQj5Ivdj/Tqa7ewsotOsorWHJRB95urE8lj7k81neGr5Z9PNmUSOa1wpVFChlP3XAHr0PuDW3XRTikrnLVk27CU5RnPFJTk6GtDGxQ13UG0zTmljCmZ2WKIN03HufYDJ/CuVg13VtPm3ux1GBuWichZB7qen4GtHxbMW1PT7bsiSTn68KP5tXmWsW99deLHW1abeqx/NGxCoh9fyJrzcRXmqtou1j6jLsHR+pe0qw5nJ2XdHs2k6zYa1EWspsyL/AKyFxtkQ+6n+fSn6tqEek6dJdSDewwscYPMjn7q/57ZrhJrWOVxKC0cyjCzRna4/EVELvU7+4Eeo3S3MVmSsL7NrMxHJb1IHGfc1pRxfPo1qc2YZLLCfvFK8fxJl8xnkmuH8y4mbfK/qfb0AHAHpTqKqXl08ZWG3XdM7BSxGViznDN+RwO+PrVHAi0CCSAQSOo9KWoreFbeLYpJOcszdWPcn3qWgGFFFFABVa9OBb+86D9as1Uvz8lufS4jz+dAGppc/2PWrSfICO3kS/wC63T8m2/rXeba83mUvC6jqRx9e3616FY3QvLG3ul6TRK/5itqb6HPWj1J9v0pyr1pM05T1rS5jY5DxXCw1q3uDgRm22Zz3DZP8xXF6QRcalqN2vzb52TeOhVcBR+jH8a2/HGv6Zq/h+4WAXkVzEh2MUXawONyn5u471xPhW/trC2uQ3nFXkG1QAQMD3PvXk4iD53LufX5ViouNKi9OW7/M7fPFU7WVpI3JPzCV1/JiKqf8JBZ/3J/++R/jVO31y0ilul2zYMxcfKO4B9fXNThtJHVnk1OhHlfU2LmY29tJLjcVGQD3qmyapa2ywfurqEXH2lyqhZGfaVGfUAHgdsVSvtctJLORFWcE7eqj+8Pep77xNbW9pNLFFK0ij5QwABPvzWtapKLXKedlmGw9WnN1uhbt9UhmlELh4Zj/AMs3GKuBsjIOa5Sz8V29+UgvrLLEEhkAIH5nj86sNd2Stut5byFvoGH88/rSjiGtJIc8sp1I89Cd15nSZPrRzWFF4ggRhHIJ3xnLbVz29/ep/wC37P8AuT/98j/GuiM1JXR5VWjKlNwka2T61XvFaS3wgyysrgfRgaof2/Z/3J/++R/jTJ9cs5LeRAs4LIQDtHHH1p3M7G1nng12XhcltAhTKny2dBg5wNxIB98GvM4fENo0EbMk+4qCflHXH1rofC3i+ws476GWO6KmVZE2ovGVwf4v9mqjJJkVIto9DwfSnLnniua/4TjSf+eN7/37T/4qnp430o5Ahvf+/a//ABVXzIw5Gf/Z
favicon: 
#自动生成的摘要长度 建议文章中手动使用 <!--more--> 效果更佳
excerpt_length: 300
# 页面    
page:
  tag_count: true

# 主题颜色
theme_color:
  primary: blue-grey 
  accent: blue

# 搜索
search:
  local: 
  path: /search.xml
  placeholder: 请输入关键字

# 不蒜子计数
busuanzi:
  site: true
  page: true
  busuanzi_js: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

# 文末结束语
passage_end_tag:
  enabled: true
  text: --- <i class="fa fa-heartbeat"></i>本文仅供参考，希望对你有所帮助<i class="fa fa-heartbeat"></i>  ---

# Google Adsense广告代码
google_adsense:
  enabled: false
  footer: ../_adsense/footer.ejs
  sidebar: ../_adsense/sidebar.ejs
  banner: ../_adsense/banner.ejs

# 数学公式渲染
math:
  enabled: true
  engine: mathjax ##可选渲染引擎：mathjax、katex
  mathjax:
    cdn: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  katex:
    cdn_css: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css
    cdn_js: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js
    auto_render: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js

# 菜单
menu:
  home: / || home
  #about: /about/ || user
  #tags: /tags/ || bookmark
  #categories: /categories/ || folder
  archives: /archives/ || archive
  #sitemap: /sitemap.xml || map

# 页脚
footer:
  since: 
  powered: true
  theme: true
  beian:
    enable: true
    icp: 
  icon:
    # 图标名使用的是Font Awesome 5.11.2, 详见: https://fontawesome.com/
    enabled: true
    name: fas fa-heart
    color: "#d9333f"

# 评论
comment:
  use: 
  ## Gitalk
  gitalk_client_id: 
  gitalk_client_secret: 
  gitalk_repo: 
  gitalk_owner: 
  gitalk_sid_type:
  gitalk_distractionFreeMode: true
  ## Disqus
  disqus_shortname:
  ## Livere
  livere_data_uid:
  ## Valine
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  ## 畅言
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:

# 社交链接
social:
  #E-Mail: mailto:15876870780@163.com || fas fa-envelope
  GitHub: https://github.com/kunfan96x || fab fa-github
  #Steam: https://steamcommunity.com/profiles/76561198346798163 || fab fa-steam
  Weibo: https://weibo.com/u/2612322661?is_all=1 || fab fa-weibo
  #Google: https://plus.google.com/yourname || google
  #Twitter: https://twitter.com/yourname || twitter
  #FB Page: https://www.facebook.com/yourname || facebook
  #VK Group: https://vk.com/yourname || vk
  #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
  #YouTube: https://youtube.com/yourname || youtube
  #Instagram: https://instagram.com/yourname || instagram
  #Skype: skype:yourname?call|chat || skype

# 分析
analytics:
  google_analytics:
    tracking_id: 
    localhost_ignored: true
  baidu_site_id:
  cnzz_site_id:
  tencent_site_id: